services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=toh
      - POSTGRES_USER=toh
      - POSTGRES_DB=toh
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  back:
    image: tour-of-heroes:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/toh?currentSchema=toh
      - SPRING_DATASOURCE_USERNAME=toh
      - SPRING_DATASOURCE_PASSWORD=toh
