spring:
  sql:
    init:
      platform: postgresql
  datasource:
    hikari:
      maxLifetime: "300000"
      maximumPoolSize: "25"
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/toh
    username: toh
    password: toh
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        default_schema: toh
        use_jdbc_metadata_defaults: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true"
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        order_updates: "true"
        jdbc:
          batch_size: "30"
        batch_versioned_data: "true"
        enable_lazy_load_no_trans: "true"
        order_inserts: "true"
        temp:
          use_jdbc_metadata_defaults: "false"
        show_sql: "false"
    open-in-view: "false"

server:
  servlet:
    contextPath: /toh/api